[package]
name = "marching_squares"
version = "0.1.0"
authors = ["Daniele D'Orazio <d.dorazio96@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]

[dev-dependencies]
image = "0.24"
marching_squares = { path = ".", features = ["svg"] }

[features]
default = []
svg = []
