version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: rustc --version
      - run: cargo build --all-targets
      - run: cargo test --all-targets
